package org.example.pages;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.SelenideElement;
import static com.codeborne.selenide.Selenide.*;

public class ExamplePage {
    // Elements - XPath locators autogenerated for example Google search page
    private SelenideElement searchInput = $("input[name='q']");
    private SelenideElement openSearchButton = $x("//a[contains(@class, \"tm-header-user-menu__item\")]");
    private SelenideElement searchButton = $("button[type='submit']");
    private SelenideElement firstArticleLink = $("h2 a");
    private SelenideElement articleTitle = $("h1");
    private SelenideElement loginButton = $x("//button[text()='Войти']");
    private SelenideElement newsSection = $x("//a[text()=\"Новости\"]");
    // Open the page
    public void openPage() {
        open("https://habr.com/ru/");
    }
    public void searchFor(String query) {
        openSearchButton.shouldBe(Condition.visible).click();
        searchInput.shouldBe(Condition.visible).setValue(query);
        searchButton.shouldBe(Condition.visible).click();
    }
    public void openFirstArticle() {
        firstArticleLink.click();
    }
    public String getArticleTitle() {
        return articleTitle.getText();
    }
    public boolean isLoginButtonVisible() {
        return loginButton.isDisplayed();
    }
    public void clickNewsSection() {
        newsSection.shouldBe(Condition.visible).click();
    }
}

